In [2]:
import numpy as np

2. Combining and Splitting Arrays

In [3]:
print("Horizoontal and Vertical Concatination")

arr1 = np.array([1 , 2 , 3])
arr2 = np.array([4 , 5 , 6])

print(arr1)
print(arr2)

horizontal = np.hstack((arr1 , arr2))

vertical = np.vstack((arr1 , arr2))

print(horizontal)
print(vertical)



Horizoontal and Vertical Concatination
[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# vstack , hstack and split vsplit and hsplit


In [10]:
print("Stack and Split Arrays")

arr1 = np.array([
    [1 ,2],
    [3 , 4],
    [5 , 6]
])

arr2 = np.array([
    [7 , 8 , 9 , 10 , 11 , 12],
    [13 , 14 , 15 , 16 , 17 , 18]

])

print(arr1)
print(arr2)

h_split = np.hsplit(arr2 , 6)

print(h_split)

Stack and Split Arrays
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[array([[ 7],
       [13]]), array([[ 8],
       [14]]), array([[ 9],
       [15]]), array([[10],
       [16]]), array([[11],
       [17]]), array([[12],
       [18]])]


# Flattern and Reshape 3D Array

In [11]:
print("Flattern and Reshape 3D Array")

arr_3d = np.array([
    [[1 , 2] , [3 , 4]],
    [[5 , 6] , [7 , 8]]
])

print(arr_3d)

print(arr_3d.shape)

flat_arr = arr_3d.flatten()

print(arr_3d)

print(flat_arr)

reshape = flat_arr.reshape(arr_3d.shape)

print(reshape)

Flattern and Reshape 3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
