#### Numpy : Filtering , Masking , Reshaping & Broadcasting

In [1]:
import numpy as np

#### Baic Filtering

In [2]:
ages = np.array([25 , 30 , 18 , 35 , 22 , 40 , 17])

adults = ages[ages >= 18]

print(adults)

[25 30 18 35 22 40]


In [3]:
adults_age = ages[(ages > 20) & (ages < 35)]

print(adults_age)

[25 30 22]


In [4]:
name = np.array(["Rahul" , "Priya" , "Amit" , "Sneha" , "Rohit" , "Anjali" , "Karan"])

selected_names = name[np.char.startswith(name, 'A') | np.char.startswith(name, 'P')]

print(selected_names)

['Priya' 'Amit' 'Anjali']


#### Bsic Masking for seelection


In [5]:
temp = np.array([28 , 32 , 35 , 30 , 22 , 38])

is_hot = temp > 30

hot_temp = temp[is_hot]

print(temp)
print(is_hot)
print(hot_temp)

[28 32 35 30 22 38]
[False  True  True False False  True]
[32 35 38]


Masking for Modification

In [6]:
temp[is_hot] = 31

print(temp)

[28 31 31 30 22 31]


np.where()

In [7]:
scores = np.array([68 , 81 , 78 , 90 , 55 , 72 , 88])

# If scores >= 75 -> pass , otherwise fail

grades = np.where(scores >= 75 , 'Pass' , 'Fail')

print(grades)
print(scores)

['Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass']
[68 81 78 90 55 72 88]


Reshaping a 1D to 2D

In [10]:
num_1d = np.array([1, 2, 3, 4])

num_2d = num_1d.reshape(1 , 4)

print(num_1d)
print(num_2d)

[1 2 3 4]
[[1 2 3 4]]


#### Broadcasting to an Array

In [11]:
prices = np.array([10 , 20 , 30])

# add 5 to every element

new_prices = prices + 5

print(prices)
print(new_prices)

[10 20 30]
[15 25 35]


#### Broadcasting a 1D array to a 2D array

In [12]:
sales = np.array([[10 , 20] , [15 , 25] , [12 , 18]])

add_value = np.array([2 , 3 , 1])

print(sales)

print(add_value)

[[10 20]
 [15 25]
 [12 18]]
[2 3 1]


In [13]:
bonues_col = add_value.reshape(3 , 1)

sales_with_bonus = sales + bonues_col

print(bonues_col)
print(sales_with_bonus)

[[2]
 [3]
 [1]]
[[12 22]
 [18 28]
 [13 19]]
